name: dspatcher
version: "1.0"
summary: Cross-Platform Graphical Tool for DSPatch
description: http://flowbasedprogramming.com

grade: devel
confinement: strict
base: core18

apps:
  dspatcher:
    command: desktop-launch DSPatcher
    environment:
      DSPATCH_PLUGINS: $SNAP/lib/dspatch/components
      DSPATCH_USER_PLUGINS: $SNAP_USER_COMMON
      WAVEREADER_FILE: $SNAP_USER_COMMON/Sample.wav
    plugs:
      - alsa
      - home
      - unity7
      - x11

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  alsa-lib:
    source: https://mirrorservice.org/sites/ftp.alsa-project.org/pub/lib/alsa-lib-1.1.6.tar.bz2
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-alisp
    - --disable-aload
    - --disable-python
    - --disable-rawmidi
    - --disable-static
    - --disable-topology
    - --disable-ucm
    - --enable-symbolic-functions
    organize:
      snap/*/current/usr/lib/*: usr/lib/
      snap/*/current/usr/share/*: usr/share/
    stage:
    - usr/include
    - usr/lib
    - usr/share/alsa
    prime:
    - usr/lib/*.so
    - usr/lib/*.so.*
    - usr/share/alsa

  dspatcher-app:
    after: [alsa-lib]
    source: .
    plugin: cmake
    build-packages:
      - python3-pip
      - python3-setuptools
      - ninja-build
    override-build: |
      pip3 install meson
      snapcraftctl build
